add_file -type verilog "./src/top.sv"

add_file -type verilog "./src/manager_logic.sv"

add_file -type verilog "./src/taxi/taxi_arbiter.sv"
add_file -type verilog "./src/taxi/taxi_axi_dma.sv"
add_file -type verilog "./src/taxi/taxi_axi_dma_rd.sv"
add_file -type verilog "./src/taxi/taxi_axi_dma_wr.sv"
add_file -type verilog "./src/taxi/taxi_axi_if.sv"
add_file -type verilog "./src/taxi/taxi_axi_interconnect.sv"
add_file -type verilog "./src/taxi/taxi_axi_interconnect_rd.sv"
add_file -type verilog "./src/taxi/taxi_axi_interconnect_wr.sv"
add_file -type verilog "./src/taxi/taxi_axis_async_fifo.sv"
add_file -type verilog "./src/taxi/taxi_axis_if.sv"
add_file -type verilog "./src/taxi/taxi_dma_desc_if.sv"
add_file -type verilog "./src/taxi/taxi_penc.sv"
add_file -type verilog "./src/taxi/taxi_sync_reset.sv"
add_file -type verilog "./src/taxi/taxi_sync_signal.sv"

add_file -type verilog "./src/convolution/back/grayscale_stream.sv"
add_file -type verilog "./src/convolution/back/ping_pong_buffer.sv"
add_file -type verilog "./src/convolution/front/demux.sv"
add_file -type verilog "./src/convolution/front/line_buffer.sv"
add_file -type verilog "./src/convolution/front/mux.sv"
add_file -type verilog "./src/convolution/front/rgb_to_grayscale_stream.sv"
add_file -type verilog "./src/convolution/middle/adder.sv"
add_file -type verilog "./src/convolution/middle/conv1d.sv"
add_file -type verilog "./src/convolution/middle/float_mult_byte.sv"
add_file -type verilog "./src/convolution/middle/scalar_product.sv"
add_file -type verilog "./src/convolution/middle/kernel_loader.sv"
add_file -type verilog "./src/convolution/middle/window.sv"
add_file -type verilog "./src/logic_conv.sv"
add_file -type other "./src/kernel.mi"

add_file -type gao "./src/gao/logic_conv.rao"
